#!/usr/bin/env bash

SSH_PRV_KEY="${SSH_PRV_KEY:$(cat ~/.ssh/id/github_auth_id_ed25519)}"
SSH_PUB_KEY="${SSH_PRV_KEY:$(cat ~/.ssh/id/github_auth_id_ed25519.pub)}"

docker build \
    -t robsdudeson/mygpo-docker-builder:latest-dev \
    --build-arg SSH_PRV_KEY="$SSH_PRV_KEY" \
    --build-arg SSH_PUB_KEY="$SSH_PUB_KEY" \
    --squash \
    .
